import os
import json
from typing import Optional, Dict, Any

from dotenv import load_dotenv
from google import genai

from app.ai.intelligence_fusion import generate_fusion, fusion_to_dict

load_dotenv()


SYSTEM_PROMPT = """
You are AlphaScope, a disciplined institutional-grade market intelligence analyst.

You interpret structured market intelligence generated by AlphaScope's rule-based engines.

Rules:
- Do not override the recommendation.
- Do not invent data.
- Do not give financial advice.
- Do not use hype language.
- Be conservative, clear, and professional.
- Explain what the system is seeing.
- Highlight risks and uncertainties.
- Return ONLY valid JSON.
- No markdown.
- No code fences.

Required JSON schema:

{
  "symbol": "",
  "executive_summary": "",
  "technical_interpretation": "",
  "fundamental_interpretation": "",
  "market_regime_interpretation": "",
  "risk_assessment": "",
  "recommendation_interpretation": "",
  "key_watch_items": [],
  "plain_english_takeaway": ""
}
"""


def get_gemini_client():
    api_key = os.getenv("GEMINI_API_KEY")

    if not api_key:
        raise ValueError("GEMINI_API_KEY not found in environment.")

    return genai.Client(api_key=api_key)


def build_user_prompt(fusion_payload: Dict[str, Any]) -> str:
    return f"""
Analyze the following AlphaScope intelligence payload.

Remember:
- The recommendation is already determined by AlphaScope's rule engine.
- Your job is to interpret it clearly.
- Do not change the recommendation.
- Do not add unsupported claims.

AlphaScope payload:

{json.dumps(fusion_payload, indent=2)}
"""


def safe_parse_json(text: str) -> Dict[str, Any]:
    cleaned = text.strip()

    if cleaned.startswith("```json"):
        cleaned = cleaned.replace("```json", "", 1).strip()

    if cleaned.startswith("```"):
        cleaned = cleaned.replace("```", "", 1).strip()

    if cleaned.endswith("```"):
        cleaned = cleaned[:-3].strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        return {
            "symbol": "UNKNOWN",
            "executive_summary": cleaned,
            "technical_interpretation": "",
            "fundamental_interpretation": "",
            "market_regime_interpretation": "",
            "risk_assessment": "",
            "recommendation_interpretation": "",
            "key_watch_items": [],
            "plain_english_takeaway": cleaned,
            "parse_warning": "Gemini response was not valid JSON."
        }


def generate_gemini_intelligence(symbol: str) -> Optional[Dict[str, Any]]:
    fusion = generate_fusion(symbol)

    if fusion is None:
        print(f"No fusion payload available for {symbol.upper()}")
        return None

    fusion_payload = fusion_to_dict(fusion)

    client = get_gemini_client()

    response = client.models.generate_content(
        model=os.getenv("GEMINI_MODEL", "gemini-2.5-flash-lite"),
        contents=[
            SYSTEM_PROMPT,
            build_user_prompt(fusion_payload),
        ],
    )

    ai_output = safe_parse_json(response.text)

    return {
        "fusion_payload": fusion_payload,
        "ai_interpretation": ai_output,
    }


def print_gemini_report(symbol: str):
    result = generate_gemini_intelligence(symbol)

    if result is None:
        return

    fusion = result["fusion_payload"]
    ai = result["ai_interpretation"]

    print("\n" + "=" * 90)
    print(f"ALPHASCOPE GEMINI INTELLIGENCE REPORT: {symbol.upper()}")
    print("=" * 90)

    print("\nRULE ENGINE OUTPUT")
    print("-" * 90)
    print(f"symbol: {fusion.get('symbol')}")
    print(f"latest_close: {fusion.get('latest_close')}")
    print(f"market_regime: {fusion.get('market_regime')}")
    print(f"technical_signal: {fusion.get('technical_signal')}")
    print(f"fundamental_quality: {fusion.get('fundamental_quality')}")
    print(f"event_risk: {fusion.get('event_risk')}")
    print(f"composite_score: {fusion.get('composite_score')}")
    print(f"recommendation: {fusion.get('recommendation')}")

    print("\nAI INTERPRETATION")
    print("-" * 90)
    print(f"executive_summary: {ai.get('executive_summary')}")
    print(f"technical_interpretation: {ai.get('technical_interpretation')}")
    print(f"fundamental_interpretation: {ai.get('fundamental_interpretation')}")
    print(f"market_regime_interpretation: {ai.get('market_regime_interpretation')}")
    print(f"risk_assessment: {ai.get('risk_assessment')}")
    print(f"recommendation_interpretation: {ai.get('recommendation_interpretation')}")

    print("\nkey_watch_items:")
    for item in ai.get("key_watch_items", []):
        print(f"- {item}")

    print("\nplain_english_takeaway:")
    print(ai.get("plain_english_takeaway"))


def main():
    test_symbols = ["SPY", "NVDA", "TSLA"]

    for symbol in test_symbols:
        print_gemini_report(symbol)


if __name__ == "__main__":
    main()
